### PR TITLE
HotFix-Analysis-Error-Msg

### PR DESCRIPTION
**Pull request by govind-basepair**
**Task:** https://app.asana.com/0/577079795655810/1199208654512733/f

### CODE REVIEW

**Comment by saurabhbp** [comment]
@govind-basepair have you considered using super's save method and override only the response parsing and error handling?

**Review by saurabhbp — CHANGES_REQUESTED** [review]
@govind-basepair have you considered using super's save method and override only the response parsing?

**Comment by govind-basepair** [comment]
I added the changes to analysis save method because this is specific to analysis. I can move it to the error parser if you say

**Comment by saurabhbp** [comment]
yeah, the core logic of the save method is the same as the save method in the Abstract class. you could just override the _parse_response method. if that works, it'll remove the duplication of code in the save method.

**Review by blasvicco — APPROVED** [review]

**Pull request merged**
